/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.form[_ngcontent-%COMP%]{\r\n  background:#fff;\r\n  box-shadow: 2px 2px 3px #aaa;\r\n}\r\nselect[_ngcontent-%COMP%]{\r\n  display: block;\r\n}'];
//# sourceMappingURL=admin.component.css.shim.ngstyle.js.map