/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './project.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../src/app/project/project.component';
const styles_ProjectComponent:any[] = [i0.styles];
export const RenderType_ProjectComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ProjectComponent,data:{}});
export function View_ProjectComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  project works!\n'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_ProjectComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-project',
      ([] as any[]),(null as any),(null as any),(null as any),View_ProjectComponent_0,
      RenderType_ProjectComponent)),i1.ɵdid(114688,(null as any),0,i2.ProjectComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const ProjectComponentNgFactory:i1.ComponentFactory<i2.ProjectComponent> = i1.ɵccf('app-project',
    i2.ProjectComponent,View_ProjectComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbHlsL0Rlc2t0b3AvbXlCbG9nL3NyYy9hcHAvcHJvamVjdC9wcm9qZWN0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9seWwvRGVza3RvcC9teUJsb2cvc3JjL2FwcC9wcm9qZWN0L3Byb2plY3QuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvbHlsL0Rlc2t0b3AvbXlCbG9nL3NyYy9hcHAvcHJvamVjdC9wcm9qZWN0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvbHlsL0Rlc2t0b3AvbXlCbG9nL3NyYy9hcHAvcHJvamVjdC9wcm9qZWN0LmNvbXBvbmVudC50cy5Qcm9qZWN0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIHByb2plY3Qgd29ya3MhXG48L3A+XG4iLCI8YXBwLXByb2plY3Q+PC9hcHAtcHJvamVjdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLDBDQUVDO01BQUE7OztvQkNGSjtNQUFBO2lDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
