/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.panel[_ngcontent-%COMP%] {\r\n  border: 0px;\r\n  border-radius: 3px;\r\n  border: 1px solid #f5f5f5;\r\n  margin:0 5%;\r\n  margin-bottom: 15px;\r\n  background:#fafafa;\r\n  box-shadow:0px 2px 2px #aaa;\r\n}\r\n.panel[_ngcontent-%COMP%]   .panel-heading[_ngcontent-%COMP%] {\r\n  background: #f5f5f5;\r\n  padding: 6px 15px;\r\n  border-bottom-color: #eee;\r\n  color: #777;\r\n}\r\n.panel-body[_ngcontent-%COMP%] {\r\n  padding: 15px;\r\n}\r\n.site[_ngcontent-%COMP%] {\r\n  margin-bottom: 12px;\r\n}\r\n.site[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]{\r\n  color: #666;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbHlsL0Rlc2t0b3AvbXlCbG9nL3NyYy9hcHAvc2l0ZXMvc2l0ZXMuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9seWwvRGVza3RvcC9teUJsb2cvc3JjL2FwcC9zaXRlcy9zaXRlcy5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
