/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.panel[_ngcontent-%COMP%] {\r\n  border: 0px;\r\n  border-radius: 3px;\r\n  border: 1px solid #f5f5f5;\r\n  margin:0 5%;\r\n  margin-bottom: 15px;\r\n  background:#fafafa;\r\n  box-shadow:0px 2px 2px #aaa;\r\n}\r\n.panel[_ngcontent-%COMP%]   .panel-heading[_ngcontent-%COMP%] {\r\n  background: #f5f5f5;\r\n  padding: 6px 15px;\r\n  border-bottom-color: #eee;\r\n  color: #777;\r\n}\r\n.panel-body[_ngcontent-%COMP%] {\r\n  padding: 15px;\r\n}\r\n.site[_ngcontent-%COMP%] {\r\n  margin-bottom: 12px;\r\n}\r\n.site[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]{\r\n  color: #666;\r\n}'];
//# sourceMappingURL=sites.component.css.shim.ngstyle.js.map