/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.topic-title[_ngcontent-%COMP%]{\r\n  font-size:1.2rem;\r\n}'];
//# sourceMappingURL=blog.component.css.shim.ngstyle.js.map