/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './blog-detail.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../src/app/blog-detail/blog-detail.component';
const styles_BlogDetailComponent:any[] = [i0.styles];
export const RenderType_BlogDetailComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_BlogDetailComponent,data:{}});
export function View_BlogDetailComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),10,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'h5',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['',''])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),0,'hr',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),3,'p',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'a',[['target','_blank']],[[8,
          'href',4]],(null as any),(null as any),(null as any),(null as any))),(_l()(),
          i1.ɵted((null as any),['链接：'])),(_l()(),i1.ɵted((null as any),['',''])),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),['\n']))],
      (null as any),(_ck,_v) => {
        var _co:i2.BlogDetailComponent = _v.component;
        const currVal_0:any = _co.blog.title;
        _ck(_v,3,0,currVal_0);
        const currVal_1:any = i1.ɵinlineInterpolate(1,'',_co.blog.content,'');
        _ck(_v,7,0,currVal_1);
        const currVal_2:any = _co.blog.content;
        _ck(_v,9,0,currVal_2);
      });
}
export function View_BlogDetailComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-blog-detail',
      ([] as any[]),(null as any),(null as any),(null as any),View_BlogDetailComponent_0,
      RenderType_BlogDetailComponent)),i1.ɵdid(114688,(null as any),0,i2.BlogDetailComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const BlogDetailComponentNgFactory:i1.ComponentFactory<i2.BlogDetailComponent> = i1.ɵccf('app-blog-detail',
    i2.BlogDetailComponent,View_BlogDetailComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbHlsL0Rlc2t0b3AvbXlCbG9nL3NyYy9hcHAvYmxvZy1kZXRhaWwvYmxvZy1kZXRhaWwuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2x5bC9EZXNrdG9wL215QmxvZy9zcmMvYXBwL2Jsb2ctZGV0YWlsL2Jsb2ctZGV0YWlsLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL2x5bC9EZXNrdG9wL215QmxvZy9zcmMvYXBwL2Jsb2ctZGV0YWlsL2Jsb2ctZGV0YWlsLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvbHlsL0Rlc2t0b3AvbXlCbG9nL3NyYy9hcHAvYmxvZy1kZXRhaWwvYmxvZy1kZXRhaWwuY29tcG9uZW50LnRzLkJsb2dEZXRhaWxDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gIDxoNT57e2Jsb2cudGl0bGV9fTwvaDU+PGhyPlxuICA8cD48YSBocmVmPVwie3tibG9nLmNvbnRlbnR9fVwiIHRhcmdldD1cIl9ibGFua1wiPumTvuaOpe+8mjwvYT57e2Jsb2cuY29udGVudH19PC9wPlxuPC9kaXY+XG4iLCI8YXBwLWJsb2ctZGV0YWlsPjwvYXBwLWJsb2ctZGV0YWlsPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQXVCLHlDQUNyQjtVQUFBO1VBQUEsZ0JBQUksd0NBQW1CO1VBQUE7VUFBQSw0Q0FBSTtVQUFBLFdBQzNCO1VBQUE7TUFBRztVQUFBLHFFQUEyQztpQkFBQSx5QkFBTztNQUFvQix1Q0FDckU7OztRQUZBO1FBQUE7UUFDRTtRQUFILFdBQUcsU0FBSDtRQUFrRDtRQUFBOzs7O29CQ0Z2RDtNQUFBO29DQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
