/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.button-collapse[_ngcontent-%COMP%]{\r\n  display: block;\r\n}\r\n.top-nav[_ngcontent-%COMP%]   img[_ngcontent-%COMP%] {\r\n  display: block;\r\n  max-height:30px;\r\n}\r\n.nav-text[_ngcontent-%COMP%]{\r\n  padding:0 15px;\r\n}'];
//# sourceMappingURL=app.component.css.shim.ngstyle.js.map