/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/app.module';
import * as i2 from '../../../src/app/app.component';
import * as i3 from './home/home.component.ngfactory';
import * as i4 from './blog/blog.component.ngfactory';
import * as i5 from './project/project.component.ngfactory';
import * as i6 from './paradise/paradise.component.ngfactory';
import * as i7 from './about/about.component.ngfactory';
import * as i8 from './sites/sites.component.ngfactory';
import * as i9 from './admin/admin.component.ngfactory';
import * as i10 from './blog-detail/blog-detail.component.ngfactory';
import * as i11 from './app.component.ngfactory';
import * as i12 from '@angular/common';
import * as i13 from '@angular/platform-browser';
import * as i14 from '@angular/forms';
import * as i15 from '@angular/router';
import * as i16 from '../../../src/app/home/home.component';
import * as i17 from '../../../src/app/blog/blog.component';
import * as i18 from '../../../src/app/project/project.component';
import * as i19 from '../../../src/app/paradise/paradise.component';
import * as i20 from '../../../src/app/about/about.component';
import * as i21 from '../../../src/app/sites/sites.component';
import * as i22 from '../../../src/app/admin/admin.component';
import * as i23 from '../../../src/app/blog-detail/blog-detail.component';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.HomeComponentNgFactory,i4.BlogComponentNgFactory,i5.ProjectComponentNgFactory,
              i6.ParadiseComponentNgFactory,i7.AboutComponentNgFactory,i8.SitesComponentNgFactory,
              i9.AdminComponentNgFactory,i10.BlogDetailComponentNgFactory,i11.AppComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i12.NgLocalization,i12.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
          i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
          i0.ɵl,([] as any[])),i0.ɵmpd(4608,i13.DomSanitizer,i13.ɵe,[i12.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i13.DomSanitizer]),i0.ɵmpd(4608,
              i13.HAMMER_GESTURE_CONFIG,i13.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i13.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i13.ɵDomEventsPlugin(p0_0),new i13.ɵKeyEventsPlugin(p1_0),
                    new i13.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i12.DOCUMENT,i12.DOCUMENT,i12.DOCUMENT,i13.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i13.EventManager,i13.EventManager,[i13.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i13.ɵDomSharedStylesHost,i13.ɵDomSharedStylesHost,
              [i12.DOCUMENT]),i0.ɵmpd(4608,i13.ɵDomRendererFactory2,i13.ɵDomRendererFactory2,
              [i13.EventManager,i13.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,
              (null as any),[i13.ɵDomRendererFactory2]),i0.ɵmpd(6144,i13.ɵSharedStylesHost,
              (null as any),[i13.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,
              i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i13.Meta,i13.Meta,[i12.DOCUMENT]),
          i0.ɵmpd(4608,i13.Title,i13.Title,[i12.DOCUMENT]),i0.ɵmpd(4608,i14.ɵi,i14.ɵi,
              ([] as any[])),i0.ɵmpd(4608,i14.FormBuilder,i14.FormBuilder,([] as any[])),
          i0.ɵmpd(5120,i15.ActivatedRoute,i15.ɵf,[i15.Router]),i0.ɵmpd(4608,i15.NoPreloading,
              i15.NoPreloading,([] as any[])),i0.ɵmpd(6144,i15.PreloadingStrategy,
              (null as any),[i15.NoPreloading]),i0.ɵmpd(135680,i15.RouterPreloader,
              i15.RouterPreloader,[i15.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i15.PreloadingStrategy]),i0.ɵmpd(4608,i15.PreloadAllModules,
              i15.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i15.ROUTER_INITIALIZER,
              i15.ɵi,[i15.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i15.ROUTER_INITIALIZER]),i0.ɵmpd(512,i12.CommonModule,i12.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i13.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i15.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i15.ɵg,i15.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i13.ɵc(p0_0,p0_1),i15.ɵh(p1_0)];
              },[[2,i13.NgProbeToken],[2,i0.NgProbeToken],i15.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i13.BrowserModule,i13.BrowserModule,[[3,i13.BrowserModule]]),
          i0.ɵmpd(512,i14.ɵba,i14.ɵba,([] as any[])),i0.ɵmpd(512,i14.FormsModule,i14.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i14.ReactiveFormsModule,i14.ReactiveFormsModule,
              ([] as any[])),i0.ɵmpd(1024,i15.ɵa,i15.ɵd,[[3,i15.Router]]),i0.ɵmpd(512,
              i15.UrlSerializer,i15.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i15.ChildrenOutletContexts,i15.ChildrenOutletContexts,([] as any[])),
          i0.ɵmpd(512,i12.LocationStrategy,i12.HashLocationStrategy,[i12.PlatformLocation,
              [2,i12.APP_BASE_HREF]]),i0.ɵmpd(512,i12.Location,i12.Location,[i12.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i15.ROUTES,() => {
            return [[{path:'',redirectTo:'home',pathMatch:'full'},{path:'home',component:i16.HomeComponent},
                {path:'blog',component:i17.BlogComponent},{path:'project',component:i18.ProjectComponent},
                {path:'paradise',component:i19.ParadiseComponent},{path:'about',component:i20.AboutComponent},
                {path:'sites',component:i21.SitesComponent},{path:'admin',component:i22.AdminComponent},
                {path:'blogDetail',component:i23.BlogDetailComponent},{path:'**',component:i16.HomeComponent}]];
          },([] as any[])),i0.ɵmpd(256,i15.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i15.Router,i15.ɵe,[i0.ApplicationRef,i15.UrlSerializer,i15.ChildrenOutletContexts,
              i12.Location,i0.Injector,i0.NgModuleFactoryLoader,i0.Compiler,i15.ROUTES,
              i15.ROUTER_CONFIGURATION,[2,i15.UrlHandlingStrategy],[2,i15.RouteReuseStrategy]]),
          i0.ɵmpd(512,i15.RouterModule,i15.RouterModule,[[2,i15.ɵa],[2,i15.Router]]),
          i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbHlsL0Rlc2t0b3AvbXlCbG9nL3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9seWwvRGVza3RvcC9teUJsb2cvc3JjL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
