/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.panel[_ngcontent-%COMP%]   p[_ngcontent-%COMP%]{\r\n  font-family: Bitter,serif;\r\n  font-size:1.5rem;\r\n}'];
//# sourceMappingURL=about.component.css.shim.ngstyle.js.map