/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './index.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../src/app/index/index.component';
const styles_IndexComponent:any[] = [i0.styles];
export const RenderType_IndexComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_IndexComponent,data:{}});
export function View_IndexComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  index works!\n'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_IndexComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-index',([] as any[]),
      (null as any),(null as any),(null as any),View_IndexComponent_0,RenderType_IndexComponent)),
      i1.ɵdid(114688,(null as any),0,i2.IndexComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const IndexComponentNgFactory:i1.ComponentFactory<i2.IndexComponent> = i1.ɵccf('app-index',
    i2.IndexComponent,View_IndexComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbHlsL0Rlc2t0b3AvbXlCbG9nL3NyYy9hcHAvaW5kZXgvaW5kZXguY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL2x5bC9EZXNrdG9wL215QmxvZy9zcmMvYXBwL2luZGV4L2luZGV4LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL2x5bC9EZXNrdG9wL215QmxvZy9zcmMvYXBwL2luZGV4L2luZGV4LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvbHlsL0Rlc2t0b3AvbXlCbG9nL3NyYy9hcHAvaW5kZXgvaW5kZXguY29tcG9uZW50LnRzLkluZGV4Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIGluZGV4IHdvcmtzIVxuPC9wPlxuIiwiPGFwcC1pbmRleD48L2FwcC1pbmRleD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLHdDQUVDO01BQUE7OztvQkNGSjtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
